services:
  application:
    image: ${DOCKER_USERNAME}/tamago-server:latest
    container_name: tamago-server
    ports:
      - "8001:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
        - tamago
    depends_on:
      - database

  database:
    image: mysql:8
    container_name: tamago-db
    ports:
      - "3301:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./tamago/db:/var/lib/mysql
    networks:
      - tamago

networks:
  tamago:
    driver: bridge