spring:
  profiles:
    active: local
  config:
    import:
      - database.yml
      - flyway.yml
      - security.yml
      - swagger.yml
      - oauth.yml
      - modulith.yml
      - aws.yml
      - weather.yml
      - fcm.yml
      - sentry.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
