management:
  endpoints:
    web:
      exposure:
        include: health

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  environment: ${spring.profiles.active:local}
  send-default-pii: true
  max-request-body-size: always
  profile-session-sample-rate: 1.0
  profile-lifecycle: trace
  exception-resolver-order: -2147483648
  logging:
    minimum-event-level: error
    minimum-breadcrumb-level: info
---
spring:
  config:
    activate:
      on-profile: prod

sentry:
  traces-sample-rate: 0.1
  profile-session-sample-rate: 0.1
  send-default-pii: false
